spring.application.name=AUTH-SERVICE
server.port=8085

# Admin credentials
spring.security.user.name=admin
spring.security.user.password=admin123


eureka.client.registry-fetch-interval-seconds=30
eureka.client.initial-instance-info-replication-interval-seconds=40

# Eureka
eureka.client.service-url.defaultZone=https://examsystem-1-jqv6.onrender.com/eureka/
